/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    committees: Committee;
    documents: Document;
    'document-categories': DocumentCategory;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    committees: CommitteesSelect<false> | CommitteesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'document-categories': DocumentCategoriesSelect<false> | DocumentCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Cada página es una lista de secciones. Agrega, reordena o elimina secciones y publica los cambios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Nombre interno y título por defecto en buscadores.
   */
  title: string;
  /**
   * Dirección de la página sin barra inicial, p. ej. «membresia» o «nosotros/quienes-somos». La portada usa «inicio».
   */
  slug: string;
  layout: (
    | PageHeroBlock
    | HomeHeroBlock
    | EventHeroBlock
    | SplitContentBlock
    | ContentBlock
    | NumberedListBlock
    | NumberedGridBlock
    | FeaturePairBlock
    | ChecklistBlock
    | IconListBlock
    | CardGridBlock
    | StatsBlock
    | MediaBlockBlock
    | VideoBlock
    | CtaBandBlock
    | PricingBlock
    | SignupStepsBlock
    | ContactSectionBlock
    | PeopleGridBlock
    | CommitteeListBlock
    | ResourceLibraryBlock
    | EventDetailsBlock
    | AgendaBlock
    | BenefitsPanelBlock
  )[];
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  title: string;
  titleSize?: ('large' | 'medium') | null;
  description?: string | null;
  buttons?:
    | {
        label: string;
        /**
         * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
         */
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Lista de enlaces a secciones de la página, a la derecha del título.
   */
  sideLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock".
 */
export interface HomeHeroBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  /**
   * Presiona Enter para forzar un salto de línea.
   */
  heading: string;
  /**
   * Parte del título que se muestra en amarillo (p. ej. «acción»).
   */
  highlight?: string | null;
  description?: string | null;
  buttons?:
    | {
        label: string;
        /**
         * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
         */
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'homeHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHeroBlock".
 */
export interface EventHeroBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  title: string;
  themeLabel?: string | null;
  theme?: string | null;
  /**
   * Número grande en amarillo (p. ej. 02).
   */
  dateNumber?: string | null;
  /**
   * Usa Enter para separar líneas.
   */
  dateLabel?: string | null;
  /**
   * Día y lugar.
   */
  detail?: string | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock".
 */
export interface SplitContentBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  style?: ('border' | 'bar' | 'plain') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  link?: {
    label?: string | null;
    /**
     * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
     */
    url?: string | null;
  };
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'splitContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedListBlock".
 */
export interface NumberedListBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  layout?: ('stacked' | 'split') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'numberedList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedGridBlock".
 */
export interface NumberedGridBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  /**
   * Se muestra antes del número (p. ej. EJE 01).
   */
  numberPrefix?: string | null;
  /**
   * Opcional, en negritas (p. ej. «Enfoque:»).
   */
  descriptionPrefix?: string | null;
  items?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'numberedGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturePairBlock".
 */
export interface FeaturePairBlock {
  /**
   * La primera tarjeta es clara y la segunda azul.
   */
  items?:
    | {
        /**
         * Etiqueta corta en mayúsculas que aparece sobre el título.
         */
        eyebrow?: string | null;
        heading: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featurePair';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock".
 */
export interface ChecklistBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'checklist';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconListBlock".
 */
export interface IconListBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  items?:
    | {
        icon?:
          | (
              | 'calendar'
              | 'clock'
              | 'map-pin'
              | 'users'
              | 'badge-check'
              | 'presentation'
              | 'file-text'
              | 'file-chart'
              | 'file-pen'
              | 'book-open'
              | 'library'
              | 'utensils'
              | 'coffee'
              | 'store'
              | 'heart-handshake'
              | 'handshake'
              | 'send'
              | 'mail'
              | 'smartphone'
              | 'megaphone'
              | 'graduation-cap'
              | 'landmark'
              | 'lightbulb'
              | 'scale'
              | 'globe'
              | 'star'
            )
          | null;
        title?: string | null;
        /**
         * Escribe **texto** para resaltarlo en negritas.
         */
        text: string;
        emphasis?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock".
 */
export interface CardGridBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  style?: ('cards' | 'columns') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  cards?:
    | {
        icon?:
          | (
              | 'calendar'
              | 'clock'
              | 'map-pin'
              | 'users'
              | 'badge-check'
              | 'presentation'
              | 'file-text'
              | 'file-chart'
              | 'file-pen'
              | 'book-open'
              | 'library'
              | 'utensils'
              | 'coffee'
              | 'store'
              | 'heart-handshake'
              | 'handshake'
              | 'send'
              | 'mail'
              | 'smartphone'
              | 'megaphone'
              | 'graduation-cap'
              | 'landmark'
              | 'lightbulb'
              | 'scale'
              | 'globe'
              | 'star'
            )
          | null;
        /**
         * Etiqueta corta en mayúsculas que aparece sobre el título.
         */
        eyebrow?: string | null;
        title: string;
        description?: string | null;
        link?: {
          label?: string | null;
          /**
           * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
           */
          url?: string | null;
        };
        /**
         * Opcional. Etiqueta pequeña al final (p. ej. «Archivo en preparación»).
         */
        status?: string | null;
        /**
         * Solo para el estilo de tarjetas grandes.
         */
        dark?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Aparece en una franja azul clara bajo las tarjetas.
   */
  note?: string | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  variant?: ('band' | 'panel') | null;
  eyebrow?: string | null;
  heading?: string | null;
  items?:
    | {
        value: string;
        /**
         * p. ej. +
         */
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockBlock".
 */
export interface MediaBlockBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  image: number | Media;
  caption?: string | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * Fotos y gráficos usados en las páginas.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  sourceUrl?: string | null;
  /**
   * Describe la imagen para personas que usan lectores de pantalla (p. ej. «Retrato de Jonnathan García»).
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  /**
   * Pega el enlace de YouTube (p. ej. https://www.youtube.com/watch?v=…).
   */
  videoUrl: string;
  channel?: {
    label?: string | null;
    /**
     * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
     */
    url?: string | null;
  };
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock".
 */
export interface CtaBandBlock {
  style?: ('mustard' | 'navy' | 'navy-deep') | null;
  /**
   * Opcional. Se muestra en un círculo a la izquierda.
   */
  icon?:
    | (
        | 'calendar'
        | 'clock'
        | 'map-pin'
        | 'users'
        | 'badge-check'
        | 'presentation'
        | 'file-text'
        | 'file-chart'
        | 'file-pen'
        | 'book-open'
        | 'library'
        | 'utensils'
        | 'coffee'
        | 'store'
        | 'heart-handshake'
        | 'handshake'
        | 'send'
        | 'mail'
        | 'smartphone'
        | 'megaphone'
        | 'graduation-cap'
        | 'landmark'
        | 'lightbulb'
        | 'scale'
        | 'globe'
        | 'star'
      )
    | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Parte del título que se muestra en amarillo (solo en fondos azules).
   */
  highlight?: string | null;
  description?: string | null;
  meta?: {
    date?: string | null;
    location?: string | null;
    format?: string | null;
  };
  buttons?:
    | {
        label: string;
        /**
         * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
         */
        url: string;
        style?: ('primary' | 'secondary') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ctaBand';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  intro?: string | null;
  plans?:
    | {
        name: string;
        price: string;
        note?: string | null;
        buttonLabel: string;
        url: string;
        featured?: boolean | null;
        /**
         * Solo para tarifas destacadas (p. ej. «Miembros»).
         */
        badge?: string | null;
        id?: string | null;
      }[]
    | null;
  callout?: {
    icon?:
      | (
          | 'calendar'
          | 'clock'
          | 'map-pin'
          | 'users'
          | 'badge-check'
          | 'presentation'
          | 'file-text'
          | 'file-chart'
          | 'file-pen'
          | 'book-open'
          | 'library'
          | 'utensils'
          | 'coffee'
          | 'store'
          | 'heart-handshake'
          | 'handshake'
          | 'send'
          | 'mail'
          | 'smartphone'
          | 'megaphone'
          | 'graduation-cap'
          | 'landmark'
          | 'lightbulb'
          | 'scale'
          | 'globe'
          | 'star'
        )
      | null;
    title?: string | null;
    text?: string | null;
    link?: {
      label?: string | null;
      /**
       * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
       */
      url?: string | null;
    };
  };
  footnote?: string | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SignupStepsBlock".
 */
export interface SignupStepsBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  formStep: {
    /**
     * Etiqueta corta en mayúsculas que aparece sobre el título.
     */
    eyebrow?: string | null;
    heading: string;
    text?: string | null;
    link?: {
      label?: string | null;
      /**
       * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
       */
      url?: string | null;
    };
    noteTitle?: string | null;
    noteText?: string | null;
  };
  paymentStep: {
    /**
     * Etiqueta corta en mayúsculas que aparece sobre el título.
     */
    eyebrow?: string | null;
    heading: string;
    methods?:
      | {
          title: string;
          /**
           * Escribe **texto** para resaltarlo en negritas.
           */
          description?: string | null;
          link?: {
            label?: string | null;
            /**
             * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
             */
            url?: string | null;
          };
          options?:
            | {
                label: string;
                price: string;
                url: string;
                id?: string | null;
              }[]
            | null;
          /**
           * Usa la dirección de Ajustes del sitio.
           */
          showPostalAddress?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'signupSteps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock".
 */
export interface ContactSectionBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * El formulario abre el programa de correo con el mensaje dirigido al primer correo de Ajustes del sitio.
   */
  form: {
    /**
     * Etiqueta corta en mayúsculas que aparece sobre el título.
     */
    eyebrow?: string | null;
    heading: string;
    note?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleGridBlock".
 */
export interface PeopleGridBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  display?: ('bios' | 'portraits') | null;
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  people?:
    | {
        name: string;
        role: string;
        photo?: (number | null) | Media;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'peopleGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommitteeListBlock".
 */
export interface CommitteeListBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  description?: string | null;
  /**
   * Opcional. Déjalo vacío para mostrar todos los comités en el orden de la colección Comités.
   */
  committees?: (number | Committee)[] | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'committeeList';
}
/**
 * Comités de trabajo. Arrastra las filas para cambiar el orden en que aparecen en la página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: number;
  _order?: string | null;
  /**
   * Sin la palabra «Comité» (p. ej. «Asuntos Legislativos»).
   */
  name: string;
  /**
   * Para enlazar a /nosotros/estructura-organizacional#este-id.
   */
  slug: string;
  description: string;
  /**
   * Opcional. Aparece en un recuadro amarillo bajo la descripción.
   */
  focus?: string | null;
  functionsLabel: string;
  functions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rellena esta sección solo si el comité tiene una junta (p. ej. Junta Editora).
   */
  board?: {
    title?: string | null;
    summary?: string | null;
    members?:
      | {
          name: string;
          role: string;
          id?: string | null;
        }[]
      | null;
    responsibilities?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  coordinator: {
    name: string;
    photo?: (number | null) | Media;
    bio: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourceLibraryBlock".
 */
export interface ResourceLibraryBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Los documentos se gestionan en Archivos › Documentos.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'resourceLibrary';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventDetailsBlock".
 */
export interface EventDetailsBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  items?:
    | {
        icon?:
          | (
              | 'calendar'
              | 'clock'
              | 'map-pin'
              | 'users'
              | 'badge-check'
              | 'presentation'
              | 'file-text'
              | 'file-chart'
              | 'file-pen'
              | 'book-open'
              | 'library'
              | 'utensils'
              | 'coffee'
              | 'store'
              | 'heart-handshake'
              | 'handshake'
              | 'send'
              | 'mail'
              | 'smartphone'
              | 'megaphone'
              | 'graduation-cap'
              | 'landmark'
              | 'lightbulb'
              | 'scale'
              | 'globe'
              | 'star'
            )
          | null;
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventDetails';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgendaBlock".
 */
export interface AgendaBlock {
  background?: ('bg' | 'surface' | 'surface-2') | null;
  heading: string;
  /**
   * Por ejemplo, Mañana y Tarde.
   */
  periods?:
    | {
        title: string;
        subtitle?: string | null;
        entries?:
          | {
              start: string;
              end: string;
              title: string;
              /**
               * Se muestra al expandir la actividad.
               */
              description?: string | null;
              /**
               * Recesos, registro o mensajes. Se muestra en gris y sin descripción.
               */
              minor?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footnote?: string | null;
  link?: {
    label?: string | null;
    /**
     * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
     */
    url?: string | null;
  };
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'agenda';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsPanelBlock".
 */
export interface BenefitsPanelBlock {
  /**
   * Etiqueta corta en mayúsculas que aparece sobre el título.
   */
  eyebrow?: string | null;
  heading: string;
  highlight?: {
    label?: string | null;
    value?: string | null;
    text?: string | null;
  };
  items?:
    | {
        icon?:
          | (
              | 'calendar'
              | 'clock'
              | 'map-pin'
              | 'users'
              | 'badge-check'
              | 'presentation'
              | 'file-text'
              | 'file-chart'
              | 'file-pen'
              | 'book-open'
              | 'library'
              | 'utensils'
              | 'coffee'
              | 'store'
              | 'heart-handshake'
              | 'handshake'
              | 'send'
              | 'mail'
              | 'smartphone'
              | 'megaphone'
              | 'graduation-cap'
              | 'landmark'
              | 'lightbulb'
              | 'scale'
              | 'globe'
              | 'star'
            )
          | null;
        title: string;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Escribe **texto** para resaltarlo en negritas.
   */
  note?: string | null;
  /**
   * Opcional. Permite enlazar directamente a esta sección (p. ej. «comites» para /pagina#comites). Solo minúsculas, números y guiones.
   */
  anchor?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefitsPanel';
}
/**
 * Boletines, comunicados y otros archivos descargables que aparecen en la biblioteca de Recursos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  sourceUrl?: string | null;
  title: string;
  category: number | DocumentCategory;
  /**
   * Los documentos más recientes aparecen primero.
   */
  publishedAt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Filtros de la biblioteca de recursos. Arrastra las filas para cambiar el orden en que aparecen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-categories".
 */
export interface DocumentCategory {
  id: number;
  _order?: string | null;
  sourceSlug?: string | null;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Personas con acceso al panel. Los administradores gestionan usuarios; los editores gestionan contenido.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Los editores pueden modificar el contenido, pero no gestionar usuarios.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'committees';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'document-categories';
        value: number | DocumentCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        pageHero?: T | PageHeroBlockSelect<T>;
        homeHero?: T | HomeHeroBlockSelect<T>;
        eventHero?: T | EventHeroBlockSelect<T>;
        splitContent?: T | SplitContentBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        numberedList?: T | NumberedListBlockSelect<T>;
        numberedGrid?: T | NumberedGridBlockSelect<T>;
        featurePair?: T | FeaturePairBlockSelect<T>;
        checklist?: T | ChecklistBlockSelect<T>;
        iconList?: T | IconListBlockSelect<T>;
        cardGrid?: T | CardGridBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        mediaBlock?: T | MediaBlockBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        ctaBand?: T | CtaBandBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        signupSteps?: T | SignupStepsBlockSelect<T>;
        contactSection?: T | ContactSectionBlockSelect<T>;
        peopleGrid?: T | PeopleGridBlockSelect<T>;
        committeeList?: T | CommitteeListBlockSelect<T>;
        resourceLibrary?: T | ResourceLibraryBlockSelect<T>;
        eventDetails?: T | EventDetailsBlockSelect<T>;
        agenda?: T | AgendaBlockSelect<T>;
        benefitsPanel?: T | BenefitsPanelBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  titleSize?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  sideLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HomeHeroBlock_select".
 */
export interface HomeHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  highlight?: T;
  description?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventHeroBlock_select".
 */
export interface EventHeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  themeLabel?: T;
  theme?: T;
  dateNumber?: T;
  dateLabel?: T;
  detail?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitContentBlock_select".
 */
export interface SplitContentBlockSelect<T extends boolean = true> {
  background?: T;
  style?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedListBlock_select".
 */
export interface NumberedListBlockSelect<T extends boolean = true> {
  background?: T;
  layout?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NumberedGridBlock_select".
 */
export interface NumberedGridBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  numberPrefix?: T;
  descriptionPrefix?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturePairBlock_select".
 */
export interface FeaturePairBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ChecklistBlock_select".
 */
export interface ChecklistBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconListBlock_select".
 */
export interface IconListBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        emphasis?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardGridBlock_select".
 */
export interface CardGridBlockSelect<T extends boolean = true> {
  background?: T;
  style?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  cards?:
    | T
    | {
        icon?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        status?: T;
        dark?: T;
        id?: T;
      };
  note?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  variant?: T;
  eyebrow?: T;
  heading?: T;
  items?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlockBlock_select".
 */
export interface MediaBlockBlockSelect<T extends boolean = true> {
  background?: T;
  image?: T;
  caption?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  videoUrl?: T;
  channel?:
    | T
    | {
        label?: T;
        url?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBandBlock_select".
 */
export interface CtaBandBlockSelect<T extends boolean = true> {
  style?: T;
  icon?: T;
  eyebrow?: T;
  heading?: T;
  highlight?: T;
  description?: T;
  meta?:
    | T
    | {
        date?: T;
        location?: T;
        format?: T;
      };
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        style?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  background?: T;
  eyebrow?: T;
  heading?: T;
  intro?: T;
  plans?:
    | T
    | {
        name?: T;
        price?: T;
        note?: T;
        buttonLabel?: T;
        url?: T;
        featured?: T;
        badge?: T;
        id?: T;
      };
  callout?:
    | T
    | {
        icon?: T;
        title?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  footnote?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SignupStepsBlock_select".
 */
export interface SignupStepsBlockSelect<T extends boolean = true> {
  background?: T;
  formStep?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              url?: T;
            };
        noteTitle?: T;
        noteText?: T;
      };
  paymentStep?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        methods?:
          | T
          | {
              title?: T;
              description?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              options?:
                | T
                | {
                    label?: T;
                    price?: T;
                    url?: T;
                    id?: T;
                  };
              showPostalAddress?: T;
              id?: T;
            };
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactSectionBlock_select".
 */
export interface ContactSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  form?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        note?: T;
        buttonLabel?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PeopleGridBlock_select".
 */
export interface PeopleGridBlockSelect<T extends boolean = true> {
  background?: T;
  display?: T;
  eyebrow?: T;
  heading?: T;
  description?: T;
  people?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        bio?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CommitteeListBlock_select".
 */
export interface CommitteeListBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  committees?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResourceLibraryBlock_select".
 */
export interface ResourceLibraryBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventDetailsBlock_select".
 */
export interface EventDetailsBlockSelect<T extends boolean = true> {
  background?: T;
  items?:
    | T
    | {
        icon?: T;
        label?: T;
        value?: T;
        id?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AgendaBlock_select".
 */
export interface AgendaBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  periods?:
    | T
    | {
        title?: T;
        subtitle?: T;
        entries?:
          | T
          | {
              start?: T;
              end?: T;
              title?: T;
              description?: T;
              minor?: T;
              id?: T;
            };
        id?: T;
      };
  footnote?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
      };
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsPanelBlock_select".
 */
export interface BenefitsPanelBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  highlight?:
    | T
    | {
        label?: T;
        value?: T;
        text?: T;
      };
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        detail?: T;
        id?: T;
      };
  note?: T;
  anchor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  description?: T;
  focus?: T;
  functionsLabel?: T;
  functions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  board?:
    | T
    | {
        title?: T;
        summary?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              id?: T;
            };
        responsibilities?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  coordinator?:
    | T
    | {
        name?: T;
        photo?: T;
        bio?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  sourceUrl?: T;
  title?: T;
  category?: T;
  publishedAt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-categories_select".
 */
export interface DocumentCategoriesSelect<T extends boolean = true> {
  _order?: T;
  sourceSlug?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  sourceUrl?: T;
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Enlaces del menú superior. Los elementos con subenlaces se muestran como menú desplegable.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label?: string | null;
        /**
         * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
         */
        url?: string | null;
        /**
         * Si agregas subenlaces, el elemento se convierte en un menú desplegable y su dirección se ignora.
         */
        children?:
          | {
              label: string;
              /**
               * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    /**
     * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
     */
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * La dirección, los correos y las redes sociales se editan en Ajustes del sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              /**
               * Ruta interna (p. ej. /membresia o /recursos#biblioteca), dirección completa (https://…) o mailto:correo@dominio.com. Los enlaces externos abren en una pestaña nueva.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * El año actual se agrega automáticamente al inicio.
   */
  copyright?: string | null;
  location?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Datos de la organización que se repiten en todo el sitio.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  organizationName: string;
  /**
   * Título de la portada en buscadores y redes sociales.
   */
  siteTitle: string;
  /**
   * Descripción por defecto en buscadores (unos 150 caracteres).
   */
  siteDescription: string;
  /**
   * Opcional. Imagen de 1200 × 630 px que aparece al compartir enlaces. Si está vacía se usa la imagen actual del sitio.
   */
  shareImage?: (number | null) | Media;
  /**
   * El primero es el principal y recibe el formulario de contacto.
   */
  emails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  postalAddress: {
    street: string;
    city: string;
    region: string;
    postalCode: string;
  };
  social?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'x';
        /**
         * Se muestra en la página de contacto (p. ej. @adpupr).
         */
        handle?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  location?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organizationName?: T;
  siteTitle?: T;
  siteDescription?: T;
  shareImage?: T;
  emails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  postalAddress?:
    | T
    | {
        street?: T;
        city?: T;
        region?: T;
        postalCode?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        handle?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}